package PolitechnikaDungeon;

public enum Action {
    ATTACK, DESCEND, DEFEND, CHOOSE_ITEM, FLEE,
    CAST_SPELL, LOOK, UNDEFINED, NEW_GAME, LOAD_GAME, QUIT, NOT_SPECIFIC, SAVING, EXITING, YES, SAVE_GAME, NO
}
